### ISSUE TITLE
Travis fails in python 3.7

### ISSUE THREAD

**Issue by ehdsouza** [watson-developer-cloud/python-sdk#612]
#### Expected behavior
A recent PR: https://github.com/watson-developer-cloud/python-sdk/pull/609 added python 3.7 which should pass in travis.

#### Actual behavior
It passes locally, but fails with following on travis:
```
BlockingIOError: [Errno 11] write could not complete without blocking
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BlockingIOError: [Errno 11] write could not complete without blocking
```
https://travis-ci.org/watson-developer-cloud/python-sdk/jobs/464662022

As a workaround tried adding the following: https://github.com/travis-ci/travis-ci/issues/8982#issuecomment-354357640, but still failed
```
 before_install:
 - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"
```

#### Steps to reproduce the problem
Enable python 3.7 in travis:
```
matrix:
  include:
    - python: '3.7'
      dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
```

#### Code snippet (Note: Do not paste your credentials)
NA

#### python version
3.7
